### ISSUE TITLE
Use CSS variables for custom site colors

### ISSUE THREAD

**Issue by brylie** [WesternFriend/westernfriend.org#597]
The Bootstrap documentation encourages the use of CSS variables for custom colors.

https://getbootstrap.com/docs/5.0/customize/css-variables/

## Task

- [ ] identify where we want to override the default Bootstrap colors, such as the primary blue
- [ ] set the corresponding variable color overrides

## Code example

The following example would turn the primary color to green.

```css
:root {
	--bs-primary: green;
	--bs-primary-rgb: 0, 128, 0;
}
```
